FROM node:12.13-alpine
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install 
COPY . .
# RUN npm run dev
RUN npm run build
CMD [ "node","dist/server.js" ]
# FROM bcgovimages/aries-cloudagent:py36-1.14-1_0.4.5
# RUN echo "Pulling bcgovimages/aries-cloudagent"